### ISSUE TITLE
go-blockdevice reports disks with ram*

### ISSUE THREAD

**Issue by frezbo** [talos-systems/go-blockdevice#113]
```yaml
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop0
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/loop0
    size: 25174016
    pretty_size: 25 MB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop1
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/loop1
    size: 438272
    pretty_size: 438 kB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: loop2
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/loop2
    size: 62959616
    pretty_size: 63 MB
    io_size: 512
    sector_size: 512
    readonly: true
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram0
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram0
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram1
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram1
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram10
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram10
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram11
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram11
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram12
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram12
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram13
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram13
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram14
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram14
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram15
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram15
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram2
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram2
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram3
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram3
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram4
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram4
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram5
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram5
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram6
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram6
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram7
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram7
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram8
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram8
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: ram9
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/ram9
    size: 4194304
    pretty_size: 4.2 MB
    io_size: 4096
    sector_size: 512
    readonly: false
    cdrom: false
    bus_path: /virtual
    sub_system: /sys/class/block
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: vda
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/vda
    size: 6442450944
    pretty_size: 6.4 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    modalias: virtio:d00000002v00001AF4
    bus_path: /pci0000:00/0000:00:06.0/virtio4
    sub_system: /sys/class/block
    transport: virtio
    rotational: true
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: vdb
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/vdb
    size: 5368709120
    pretty_size: 5.4 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    modalias: virtio:d00000002v00001AF4
    bus_path: /pci0000:00/0000:00:07.0/virtio5
    sub_system: /sys/class/block
    transport: virtio
    rotational: true
---
node: 10.5.0.3
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: vdc
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-16T06:43:17Z
    updated: 2024-10-16T06:43:17Z
spec:
    dev_path: /dev/vdc
    size: 5368709120
    pretty_size: 5.4 GB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    modalias: virtio:d00000002v00001AF4
    bus_path: /pci0000:00/0000:00:08.0/virtio6
    sub_system: /sys/class/block
    transport: virtio
    rotational: true
```

```bash
Client:
	Tag:         v1.8.1
	SHA:         477752fe
	Built:       
	Go version:  go1.22.8
	OS/Arch:     linux/arm64
Server:
	NODE:        10.5.0.3
	Tag:         v1.8.0-alpha.2-70-ga9bff3a1d
	SHA:         a9bff3a1
	Built:       
	Go version:  go1.23.2
	OS/Arch:     linux/arm64
	Enabled:     RBAC
```
