### ISSUE TITLE
Bus path matcher incorrectly assumes file path suffix, causing Talos to fail to match NVMe drives

### ISSUE THREAD

**Issue by solidDoWant** [talos-systems/go-blockdevice#114]
When getting information about available disks, [this line](https://github.com/siderolabs/go-blockdevice/blob/134c41be6f4c498a149b8098fa8d862c5c47ca54/blockdevice/util/disk/disks.go#L146) trims `block/<device name>` from the bus path. For example, it changes `/pci0000:00/0000:00:03.2/0000:06:00.0/host11/port-11:0/expander-11:0/port-11:0:0/end_device-11:0:0/target11:0:0/11:0:0:0/block/sda` into `/pci0000:00/0000:00:03.2/0000:06:00.0/host11/port-11:0/expander-11:0/port-11:0:0/end_device-11:0:0/target11:0:0/11:0:0:0/`.

The problem is that not all block devices have a `block/<device name>` path. Specifically, NVMe drives have a suffix of `nvme<dev number>/nvme<dev number>n<namespace number>`. For example, for a device named `nvme0n1`, the suffix would be `nvme0/nvme0n1`.

This can be confirmed with Talos, which is affected by the aforementioned issue. The command `talosctl get disks` handles this correctly for some reason. Here's an example output for one of my NVMe drives:
```yaml
---
node: 
metadata:
    namespace: runtime
    type: Disks.block.talos.dev
    id: nvme1n1
    version: 1
    owner: block.DisksController
    phase: running
    created: 2024-10-27T02:28:38Z
    updated: 2024-10-27T02:28:38Z
spec:
    dev_path: /dev/nvme1n1
    size: 2000398934016
    pretty_size: 2.0 TB
    io_size: 512
    sector_size: 512
    readonly: false
    cdrom: false
    model: PCIe SSD
    serial: "23101720000337"
    wwid: eui.6479a7846ac018dd
    bus_path: /pci0000:00/0000:00:1d.0/0000:58:00.0/nvme
    sub_system: /sys/class/block
    transport: nvme
```

However, if I specify `busPath: /pci0000:00/0000:00:1d.0/0000:58:00.0/nvme` in my node configuration, `talosctl apply-config` fails with `no disk found matching provided parameters`. Setting it to `busPath: /pci0000:00/0000:00:1d.0/0000:58:00.0/nvme/nvme1/nvme1n1` works as expected.

It should also be trivial to check the structure of this file tree by running `ls -l /sys/block/<some nvme dev>` on any Linux system with a NVMe drive installed.
